### PR TITLE
Add Cookie-based authentication

### LINKED ISSUE #56: Implement Authentication using Slack OAuth
- [x] Integrate Slack OAuth with existing backend (#45 )
- [ ] Implement Cookie based Authentication across all routes (#57 )
- [ ] #58

### PR DESCRIPTION
**Pull request by chirag-ghosh**
closes #56 , #58

### CODE REVIEW

**Review by lurkingryuu — CHANGES_REQUESTED** [review]
The images were not loading for me, was that not integrated yet in the base branch? look at @shadowwarriorpro3003 's message
image

The original being: 
image

**Comment by chirag-ghosh** [comment]
Did you clear the db and run the digester again? Changes are there as well.

**Comment by lurkingryuu** [comment]
> Did you clear the db and run the digester again? Changes are there as well.

My bad, that solved the issue

**Review by lurkingryuu — DISMISSED** [review]

**Review by lurkingryuu — APPROVED** [review]
LGTM!

**Pull request merged**
