### PR TITLE
Harsh/tummy query refactor

### PR DESCRIPTION
**Pull request by harshkhandeparkar**

### CODE REVIEW

**Comment by YoganshSharma** [comment]
Is this really needed?
-  All of those queries would be used only once. 
- I had argue it would be more readable to see the sql queries directly in handler as it would make it clear where the data is coming from.

**Comment by harshkhandeparkar** [comment]
> Is this really needed?

Nothing is really needed, but I felt it simplified the code. I also got to use some rust features and I enjoyed it. I also have plans to refactor it further to reduce redundancies in the queries (eg: the last two message queries have too much in common)

>     * I had argue it would be more readable to see the sql queries directly in handler as it would make it clear where the data is coming from.

No. That's disgusting.

**Review by YoganshSharma — APPROVED** [review]
LGTM

**Comment by harshkhandeparkar** [comment]
> Is this really needed?
> 
>     * All of those queries would be used only once.

Tbh, it isn't necessary but I thought it makes the code look a bit cleaner. I took a bit of inspiration from [iqps](https://github.com/metakgp/iqps-go/blob/main/backend/sql/indexes.sql). Might be helpful to keep the queries separate if we are going to have a search feature later because those queries can get [long](https://github.com/metakgp/iqps-go/blob/12265c49c929b7f6ef1c81100108214f7f622b31/backend/main.go#L123).

>     * I had to argue it would be more readable to see the sql queries directly in handler as it would make it clear where the data is coming from.

Yes but the `routing.rs` file is already quite long, separating would keep it cleaner.

**Review by chirag-ghosh — APPROVED** [review]

**Pull request merged**
